### ISSUE TITLE
How can you display "actions" i.e. edit and delete buttons on the table ? 

### ISSUE THREAD

**Issue by helixaros** [TheRealVizard/django-table-sort#24]

**Comment by TheRealVizard** [comment]
Please provide a code example of what you are currently doing and what you expect to happen.

**Comment by helixaros** [comment]
Hi @TheRealVizard, from my understanding the table in constructed by using the model's fields, however sometimes you want to add plain html i.e. to trigger button actions.
Does the existing code, allows for abstract HTML to be passed on as table row (screenshot of such example)?

<img width="173" alt="Screenshot 2023-01-08 at 9 28 17 AM" src="https://user-images.githubusercontent.com/5782958/211185327-010a32cc-5bfb-4fe4-90e8-96fdbe10b8c2.png">

**Comment by TheRealVizard** [comment]
You can use the `added_columns` in your table declaration.

```
.....    
    def html_content()->str:
        return '<div><i class="button-action"></i></div>'

    ......
    TableSort(
     ......
         added_columns=[
             (("extra_col", ""), html_content),
         ]
    )
    ......
```

**Comment by helixaros** [comment]
once again thank you! thats really helpful :)

**Comment by helixaros** [comment]
I have a follow up question on my previous issue I opened. The example you provided I cannot pass the "object" being edited/deleted" i.e. {% url 'delete' object.pk %}.
This is because we passing a simplehtml, that didn't go through the loop of the objects before being pass in to the Table. 

If that can be done, can you explain how can I accomplish that? Thank you in advance.

**Comment by TheRealVizard** [comment]
Hi @helixaros the function you pass in the `added_columns` kwarg should have an `instance` arg this is the instance for the given row. Then you can use the `reverse` function to get the appropriate URL.

```
    def html_content(instance)->str:
        return f'<a href="{reverse("app:model_delete",args=instance.pk)}">Delete Instance</a>'

    ......
    TableSort(
     ......
         added_columns=[
             (("extra_col", ""), html_content),
         ]
    )
    ......
```
